# Generated by Django 4.2.6 on 2024-05-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='popularity',
            new_name='review_score',
        ),
    ]
