# Generated by Django 4.2.6 on 2024-05-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='profile_image',
            field=models.TextField(null=True),
        ),
    ]
