# Generated by Django 4.2.6 on 2024-05-16 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='profile_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='snapshot',
            field=models.TextField(blank=True),
        ),
    ]
